version: 1.0

representation:
  side_panel:
    label: "[Data] Prometheus Default Scraper Configuration"
  node:
    label:
      static: "[Data] Prometheus Default Scraper Configuration"
      template: "[Data] Prometheus Default Scraper Configuration"
    display_type: default

discovery:
  type: data_aws_prometheus_default_scraper_configuration
  dnd_supported: false
